### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai201-kalarashan#10]
https://drive.google.com/file/d/1JyDN82JcLyx0T7sfTc0DpPWHgLITt2Rg/view?usp=sharing

**Comment by Procentguide2** [comment]
Завдання 1
Стан фізичного здоров'я
Для споживача присутні зрозумілі пояснення як слідкувати за здоров'ям, тому усе зрозуміло
користувач може сам розуміти свій стан здоров'я за допомогою того, як він себе фізично почуває, тому усе актуально

Завдання 2
Мета "Забезпечити доступність у поліпшені фізичного стану та чистоти повітря для отримання нової інформаціі для написання художньої літератури"

Перший прецедент "надати позицію" наближає користувача пп до досягнення мети тим, що він допомогає системі надати доступ до необхідної інформації

Другий прецедент "онлайн повідомлення" наближає користувача пп до досягнення мети тим, що він надає нову інформацію про чистоту повітря кожен день

Третїй прецедент "надати найближчі зали" дозволяє користувачу знайти залу для поліпшення свого стану здоров'я

**Comment by oleksandrblazhko** [comment]
Оцінка  =3 бали
