### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by Procentguide2** [oleksandrblazhko/ai201-kalarashan#13]

**Comment by Procentguide2** [comment]
Завдання 1

Порушення атомарності. Об'єднаємо вимоги 1.1 та 1.3, отримуємо "Користувач надає ПП своє місцезнаходження користувач отримає інформацію про чистоту повітря".
Порушення завершенності. Перетворимо вимогу 2.3 та отримуємо "користувач отримує карту з розташуванням об'єктів". Зміст вимоги не дає зрозуміти, які об'єкти нам потрібні. 
Порушення безкоштовності реалізації. Перетворимо вимогу 2.2 на "пп знаходить найближчі зали за допомогою запиту з бази даних"

**Comment by Procentguide2** [comment]
Завдання 2

Розподілена система має вагу 2, бо є розподілений опис архітектури, де кожен сервіс буде відповідати за виконання своїх обовязків (компютер з операційною системою, сервер лінукс, монгодб).

Спеціальні вимоги до навчання корисувачів має вагу 1, бо такий актор, як - Спортсмен-письменник не потребує ніяких складних дій, окрім натискання кнопки надання місце розташування тому це не потребує навчання

**Comment by oleksandrblazhko** [comment]
Коментарі до рішення 1-го завдання:
1) умова "атомарність" порушується, якщо описано декілька дій зразу
2) умова "завершеність" порушується, якщо немає формату Subject-Action-Object
3) "безкоштовніть реалізації" порушується, якщо, наприклад, 
використовуються графічний інтерфейс
У вас не всі завдання виконано правильно.

Оцінка = 2 бали
